### ISSUE TITLE
请问，不设置endpoint的话，可以执行写在actions.py中的自定义action吗

### ISSUE THREAD

**Issue by wzlsquall** [Emmonss/weather_online_chatbot#1]
请问，不设置endpoints的话，可以执行写在actions.py中的自定义action吗

我现在运行的时候会提示没有设置endpoints

**Comment by Emmonss** [comment]
> 请问，不设置endpoints的话，可以执行写在actions.py中的自定义action吗
> 
> 我现在运行的时候会提示没有设置endpoints

这个是10.4版本的，不用写endpoint。以后可能会更新到新版本吧
