### ISSUE TITLE
最近一直研究rasa，关于对话逻辑这块，咱俩可以交流交流

### ISSUE THREAD

**Issue by zhangyanbo2007** [Emmonss/weather_online_chatbot#2]
我的微信号15821444815，还望可以加我，交流一下哈，谢谢！

**Comment by Emmonss** [comment]
这个方向我已经停更很久了＼（〇_ｏ）／。并且我现在毕业工作的方向也不是这个…所以不好意思了哈。

**Comment by Emmonss** [comment]
这个方向我已经停更很久了＼（〇_ｏ）／。并且我现在毕业工作的方向也不是这个…所以不好意思了哈。
